name: GKE Deployment

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: learning-414204

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      
      - name: Terraform Initialization
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
      
      - name: Terraform apply
        run: terraform apply -auto-approve
      
      - name: Configure Google Cloud credentials
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.0 
        with:
          service_account_key: ${{ secrets.GCP_TERRAFORM_CREDS }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Authenticate with GKE
        run: gcloud container clusters get-credentials us-central1-gke --region us-central1 --project ${{ env.PROJECT_ID }}

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Add ingress-nginx Helm repository
        run: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

      - name: Build chart dependencies
        run: helm dependency build demo-app

      - name: Check if demo-app is already installed
        id: helm_status
        run: |
          helm status demo-app || echo "status=not_installed" >> $GITHUB_ENV

      - name: Install or Update demo-app chart
        run: |
          if [[ "${{ steps.helm_status.outputs.status }}" == "not_installed" ]]; then
            helm install demo-app demo-app --namespace default --values demo-app/values.yaml
          else
            helm upgrade demo-app demo-app --namespace default --values demo-app/values.yaml
          fi
