name: Trigger Deployment

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        uses: actions/github-script@v5
        with:
          script: |
            const workflowName = 'GKE Deployment';
            const branchName = 'main';
            const response = await github.workflow.createDispatch({
              workflow_id: workflowName,
              ref: branchName
            });
            console.log(`Deployment workflow triggered: ${response.status}`);
